### ISSUE TITLE
checks of EVENTS: present_on_admission should be non mandatory

### ISSUE THREAD

**Issue by RosaMGini** [IMI-ConcePTION/Level-1-checks#5]
dear vjola, we are finalising our Level 1 checks, and there is an issue that we suggest to fix

present_on_admission is a non-mandatory variable of EVENTS. this is because the information cannot be imputed if it is missing from the original data

indeed, this is the case in the ARS data source, in many records

cheers, rosa and claudia

**Comment by clobart** [comment]
It's not mandatory to put "No", so I'll change the ETL and leave empty if it's not know.

**Comment by vjolahoxhaj** [comment]
Indeed that variable is not mandatory and the check compares the actual values to the fixed vocabularies and gives a warning when only one type of the vocabulary is present
