### ISSUE TITLE
33G MEDICINES

### ISSUE THREAD

**Issue by jingzh95** [IMI-ConcePTION/Level-1-checks#9]
@vjolahoxhaj @LAMaglan
Hi Vjola,
we got message in the html file saying that the file is too big for checking duplicates.
Would it be helpful if remove some non-mandatory variables e.g. prescriber's speciality?
Best, Jing

**Comment by vjolahoxhaj** [comment]
Dear Jing,
No please don’t remove any variables. I am back Monday and we can have a
call to have a look at it. We can switch off the duplicates check or modify
it to fit your needs.
Best,
Vjola

**Comment by jingzh95** [comment]
Thanks for the prompt reply! OK! Meanwile I will make sure  there is no duplicates in each of the separated (20) files! Best, Jing

**Comment by jingzh95** [comment]
@vjolahoxhaj @LAMaglan
Morning Vjola and Luigi,
For a call, I'm flexible today's afternoon from 1pm (preferably before 3:30) today.:) Best, Jing
